name = "precious-list"
type = "javascript"
main = "dist/server.js"
compatibility_date = "2024-11-01"
node_compat = true

[build]
command = "npm run build"
cwd = "./"

[env.production]
vars = { NODE_ENV = "production" }
