name = "precious-list"
main = "server.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install"
cwd = "./"

[env.production]
vars = { NODE_ENV = "production" }
